export const ModalStyles = {
  parts: [
    "body",
    "dialog",
    "footer",
    "header",
    "overlay",
    "closeButton",
    "dialogContainer",
  ],
  baseStyle: {},
  variants: {
    dailyHugsDesktopModal: {
      body: { borderRadius: "28px", w: "398px" },
      dialog: {
        bg: "neutral.900",
        color: "neutral.50",
        padding: "0px",
        borderWidth: "1px",
        position: "absolute",
        borderRadius: "28px",
        borderColor: "neutral.850",
        w: "398px",
        height: "216px",
        boxShadow: "0px 16px 28px rgba(0, 0, 0, 0.3)",
      },
      overlay: { bg: "#000000B3", padding: "0px" },
      closeButton: {
        position: "absolute",
        color: "neutral.200",
        _hover: { bg: "neutral.900" },
        _focus: { outline: "none" },
        width: "48px",
        height: "48px",
        borderRadius: "4px",
        top: "16px",
        right: "16px",
      },
      header: {
        px: "0px",
        py: "16px",
        borderBottom: "1px",
        borderColor: "neutral.850",
      },
      footer: {
        bg: "neutral.800",
        py: "28px",
        px: "28px",
        justifyContent: "start",
      },
    },
    dailyHugsMobileModal: {
      body: {
        borderTopRadius: "28px",
        position: "absolute",
        bottom: 0,
        marginBottom: 0,
        w: "full",
      },
      dialog: {
        bg: "neutral.50",
        color: "neutral.50",
        padding: "0px",
        borderWidth: "1px",
        borderTopRadius: "28px",
        position: "absolute",
        bottom: 0,
        marginBottom: 0,
        borderColor: "neutral.850",
        w: "full",
        boxShadow: "0px 16px 28px rgba(0, 0, 0, 0.3)",
      },
      overlay: { bg: "#000000B3", padding: "0px" },
      closeButton: {
        position: "absolute",
        color: "neutral.200",
        _hover: { bg: "neutral.900" },
        _focus: { outline: "none" },
        width: "48px",
        height: "48px",
        borderRadius: "4px",
        top: "16px",
        right: "16px",
      },
      header: {
        px: "0px",
        py: "16px",
        borderBottom: "1px",
        borderColor: "neutral.850",
      },
      footer: {
        bg: "neutral.800",
        py: "28px",
        px: "28px",
        justifyContent: "start",
      },
    },
    dailyHugsDesktopModal2: {
      body: { px: "32px", pt: "0px", pb: "32px" },
      dialog: {
        bg: "neutral.900",
        color: "neutral.50",
        padding: "0px",
        borderWidth: "1px",
        borderRadius: "20px",
        borderColor: "neutral.850",
        minW: "498px",
        boxShadow: "0px 16px 28px rgba(0, 0, 0, 0.3)",
      },
      overlay: { bg: "#000000B3", padding: "0px" },
      closeButton: {
        position: "absolute",
        color: "neutral.200",
        _hover: { bg: "neutral.900" },
        _focus: { outline: "none" },
        width: "48px",
        height: "48px",
        borderRadius: "4px",
        top: "16px",
        right: "16px",
      },
      header: {
        px: "0px",
        py: "16px",
        borderBottom: "1px",
        borderColor: "neutral.850",
      },
      footer: {
        bg: "neutral.800",
        py: "28px",
        px: "28px",
        justifyContent: "start",
      },
    },
    dailyHugsobileModal2: {
      body: {
        px: "24px",
        pt: "0px",
        pb: "24px",
        overflow: "scroll",
        borderRadius: "0px",
      },
      dialog: {
        bg: "neutral.900",
        color: "neutral.50",
        borderWidth: "0px",
        borderRadius: "0px",
        borderColor: "neutral.850",
        minW: "100%",
        height: "100vh",
        position: "fixed",
        margin: "0px",
        boxShadow: "0px 16px 28px rgba(0, 0, 0, 0.3)",
      },
      overlay: { bg: "#000000B3", padding: "0px" },
      closeButton: {
        position: "absolute",
        color: "neutral.200",
        _hover: { bg: "neutral.850" },
        _focus: { outline: "none" },
        width: "48px",
        height: "48px",
        top: "16px",
        right: "8px",
      },
      header: {
        px: "0px",
        pt: "16px",
        pb: "0px",
        borderBottom: "1px",
        borderColor: "neutral.850",
      },
      footer: { bg: "neutral.800", p: "12px", justifyContent: "start" },
    },
  },
};
